services:
  postgres:
    image: postgres
    container_name: unical_postgres
    restart: always
    environment:
      POSTGRES_USER: unical_user
      POSTGRES_PASSWORD: unical_password
      POSTGRES_DB: unical_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unical_user -d unical_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: unical_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
